_wandb:
    value:
        cli_version: 0.24.0
        e:
            wyjaklw4m6yx1ss4cmpeqqxkkhk0ev45:
                args:
                    - --model=roberta-base
                    - --task=cola
                    - --agg_type=ours_vera
                    - --vera
                    - --num_clients=3
                    - --r=4
                    - --rounds=2
                    - --lr=1e-3
                    - --local_epochs=1
                codePath: fed_train_glue.py
                codePathLocal: fed_train_glue.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1023954288640"
                        used: "73284714496"
                email: julian.pmenon@proton.me
                executable: C:\Users\jujuj\anaconda3\envs\fedex-lora\python.exe
                git:
                    commit: ea7e669e591039e7b278c48d9c36bfd147882ed8
                    remote: https://github.com/JulianPMenon/fedex-lora.git
                host: Butler
                memory:
                    total: "16716922880"
                os: Windows-10-10.0.26200-SP0
                program: D:\IML\fedex-lora\fed_train_glue.py
                python: CPython 3.10.19
                root: D:\IML\fedex-lora
                startedAt: "2026-01-26T16:41:27.785762Z"
                writerId: wyjaklw4m6yx1ss4cmpeqqxkkhk0ev45
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 16
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.44.2
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
agg_type:
    value: ours_vera
batch_size:
    value: 128
bias:
    value: none
d_initial:
    value: 0.1
fan_in_fan_out:
    value: false
init_weights:
    value: true
layers_pattern:
    value: null
layers_to_transform:
    value: null
local_epochs:
    value: 1
lora_alpha:
    value: 8
lora_dropout:
    value: 0.1
lr:
    value: 0.001
max_seq_length:
    value: 512
model:
    value: roberta-base
modules_to_save:
    value: null
num_clients:
    value: 3
projection_prng_key:
    value: 0
r:
    value: 4
rounds:
    value: 2
rslora:
    value: false
save_projection:
    value: true
seed:
    value: 42
task:
    value: cola
vera:
    value: true
vera_dropout:
    value: 0
warmup_ratio:
    value: 0.06
